const UPPER_CASE_LOWER_BOUND = 'A'.charCodeAt(0);
const UPPER_CASE_UPPER_BOUND = 'Z'.charCodeAt(0);

const LOWER_CASE_LOWER_BOUND = 'a'.charCodeAt(0);
const LOWER_CASE_UPPER_BOUND = 'z'.charCodeAt(0);

const LETTERS_IN_ALPHABET = 26;

module.exports = {
  UPPER_CASE_LOWER_BOUND,
  UPPER_CASE_UPPER_BOUND,
  LOWER_CASE_LOWER_BOUND,
  LOWER_CASE_UPPER_BOUND,
  LETTERS_IN_ALPHABET,
};
